spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    
logging:
  level:
    root: DEBUG
    com.va.spring.rest: DEBUG

springdoc:
  api-docs:
    version: "openapi_3_0"
